### ISSUE TITLE
Crafting Recipes Not Working and Hammers Behave Like Pickaxes

### ISSUE THREAD

**Issue by zamtuho** [Command17/Hammering#3] opened 2024-12-01 04:31 UTC
Describe the bug
The crafting recipes for the hammers do not work. When I try to craft a hammer using the described recipe (two blocks of the material, one ingot, and two sticks), nothing is crafted. Additionally, when I obtain a hammer through the creative menu, it does not function as expected (breaking blocks in a 3x3 area). Instead, it behaves like a regular pickaxe without any special abilities.

To Reproduce

Open a crafting table.
Attempt to craft any hammer using the described recipe.
Observe that no hammer is crafted.
Obtain a hammer from the creative menu.
Use the hammer to mine blocks and notice it does not break blocks in a 3x3 area.
Expected behavior
Hammers should be craftable using the described recipes. When used, they should break blocks in a 3x3 area as described in the mod's documentation.

Screenshots
Unfortunately, I do not have a screenshot of the issue.

Full Mod Version
1.0.0a.beta.1+mc1.21.3+fabric

Additional context
I am sorry if there are any mistakes in my explanation, as English is not my first language (I speak Spanish). Please let me know if you need any additional information to investigate this issue.

**Comment by uuComma** [comment] 2024-12-01 08:12
>Additionally, when I obtain a hammer through the creative menu, it does not function as expected (breaking blocks in a 3x3 area). Instead, it behaves like a regular pickaxe without any special abilities.

This is intended, as the special ability is an enchantment

For the other thing, that is not intended, will be fixed soon when I reproduce the bug

**Comment by uuComma** [comment] 2024-12-01 08:27
The recipes are fixed (I hope)

**Closed as completed by uuComma** 2024-12-01 08:27 UTC
Labels: bug

**Comment by uuComma** [comment] 2024-12-01 08:32
I forgot to change the changelog
